on:
  push:
    branches:
      - master
    paths:
      - 'SnowReport/**'
      - '.github/workflows/snowreport.yml'

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest
    name: Build and Deploy

    steps:
      - name: Checkout Changes
        uses: actions/checkout@v1

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.100

      - name: Build and Publish
        run: dotnet publish SnowReport --configuration Release

      - name: Deploy
        if: github.ref == 'refs/heads/master'
        uses: azure/webapps-deploy@v1
        with:
          app-name: crabuse-snowreport
          publish-profile: ${{ secrets.azureWebAppPublishProfile }}
          package: './SnowReport/bin/Release/netcoreapp3.1/publish'